site_name: CodeIgniter DEA Rule
site_description: Documentation for Temporary & Disponsable Emails Validation In CodeIgniter4

theme:
  name: material
  logo: assets/flame.svg
  favicon: assets/favicon.ico
  icon:
    repo: fontawesome/brands/github
  font:
    text: Raleway
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep orange
      accent: orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep orange
      accent: orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - toc.integrate 
    - content.code.copy
    - navigation.footer
    - content.action.edit
    - navigation.top
    - search.suggest
    - search.highlight
    - search.share

extra:
  homepage: https://codeigniter4.ir
  generator: false

  social:
    - icon: material/github
      link: https://github.com/datamweb/codeigniter-dea-rule
      name: GitHub
    - icon: material/twitter
      link: https://twitter.com/datamweb
      name: X
    - icon: material/forum
      link: https://forum.codeigniter.com
      name: Forum Codeigniter
    - icon: material/slack
      link: https://join.slack.com/t/codeigniterchat/shared_invite/zt-244xrrslc-l_I69AJSi5y2a2RVN~xIdQ
      name: Slack


repo_url: https://github.com/datamweb/codeigniter-dea-rule
edit_uri: edit/develop/docs/
copyright: Copyright &copy; 2023 Pooya Parsa Dadashi(Datamweb).

markdown_extensions:
  - pymdownx.superfences
  - pymdownx.highlight:
      use_pygments: false
  - admonition
  - pymdownx.details

extra_css:
  - https://cdn.jsdelivr.net/gh/highlightjs/cdn-release@11.8.0/build/styles/default.min.css
  - assets/css/dark_mode.css

extra_javascript:
  - https://cdn.jsdelivr.net/gh/highlightjs/cdn-release@11.8.0/build/highlight.min.js
  - assets/js/hljs.js

plugins:
  - search
  - git-revision-date-localized:
      enable_creation_date: true

nav:
  - Home: index.md
  - Installation: install.md
  - How To Use: how_to_use.md